import Head from "next/head";
import React from "react";
import NavBar from "../components/NavBar";

export default function MainLayout({ children, title = "Stats Hub" }) {
	return (
		<main className=" text-gray-600">
			<Head>
				<title>{title}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<NavBar />

			{children}
		</main>
	);
}
